apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: nodejs-app
        image: us.icr.io/cloud-images/nodejs-app:stage
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        env:
          - name: "AUTHORS_API_KEY"
            valueFrom:
              secretKeyRef:
                name: authors-secret-api
                key: AUTHORS_API_KEY
      imagePullSecrets:
        - name: default-us-icr-io