apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-nodejs-app
spec:
  inputs:
    resources:
      - name: source
        type: git
  steps:
    - name: deploy-app
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(inputs.resources.source.path)/ci-cd-pipeline/kubernetes-tekton/deploy.yaml"

